version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - Master
    - BugFixes
  
# scripts that are called at very beginning, before repo cloning  
install:
 - ps: .\InstallLatestWMF5.0.ps1
 - ps: Restart-Computer -Force
 - ps: $PSVersionTable
 
build:
  verbosity: normal
