version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - Master
    - BugFixes
  
# scripts that are called at very beginning, before repo cloning  
init:
- ps: $confirmationPage = 'http://www.microsoft.com/en-us/download/' +  $((invoke-webrequest 'http://aka.ms/wmf5latest' -UseBasicParsing).links | ? Class -eq 'mscom-link download-button dl' | % href)    # Parse confirmation page and look for URL to file
- ps: $directURL = (invoke-webrequest $confirmationPage -UseBasicParsing).Links | ? Class -eq 'mscom-link' | ? href -match "WindowsBlue-KB\d\d\d\d\d\d\d-x64.msu" | % href | select -first 1
- ps: $download = invoke-webrequest $directURL -OutFile $env:Temp\wmf5latest.msu
- ps: if (test-path $env:Temp\wmf5latest.msu)
- ps: {
- ps:   start -wait $env:Temp\wmf5latest.msu -argumentlist '/quiet /norestart'
- ps: }
- ps: else
- ps: {
- ps:    throw 'the update file is not available at the specified location'
- ps: }
- ps: Remove-Item $env:Temp\wmf5latest.msu
- ps: Restart-Computer -Force
- ps: $PSVersionTable

build:
  verbosity: normal
