version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - Master
    - BugFixes
  
# scripts that are called at very beginning, before repo cloning  
install:
 ps: |
    $confirmationPage = "http://www.microsoft.com/en-us/download/" +  $((invoke-webrequest "http://aka.ms/wmf5latest" -UseBasicParsing).links | ? Class -eq "mscom-link download-button dl" | % href)
    $directURL = (invoke-webrequest $confirmationPage -UseBasicParsing).Links | ? Class -eq "mscom-link" | ? href -match "WindowsBlue-KB\d\d\d\d\d\d\d-x64.msu" | % href | select -first 1
    $download = invoke-webrequest $directURL -OutFile $env:Temp\wmf5latest.msu
    if (test-path $env:Temp\wmf5latest.msu) {
        start -wait $env:Temp\wmf5latest.msu -argumentlist "/quiet /norestart"
    }
    else {
        throw "WMF5.0 update file is not available at the specified location"
    }
    Remove-Item $env:Temp\wmf5latest.msu
    Restart-Computer -Force
    $PSVersionTable
    
build:
  verbosity: normal
