variables:
  # Avoid expensive initialization of dotnet cli, see: https://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
steps:
- pwsh: |
    Import-Module .\tools\appveyor.psm1; Invoke-AppveyorInstall;
    ./build.ps1 -Configuration 'Release' -PSVersion 6
  displayName: 'Build'
- template: templates/test.yaml
