variables:
  pwsh: true
  # Avoid expensive initialization of dotnet cli, see: https://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
jobs:
  - job: 'Ubuntu_16.04'
    pool:
      vmImage: ubuntu-16.04
    steps:
    - template: templates/unix.yaml
  - job: 'Ubuntu_18.04'
    pool:
      vmImage: ubuntu-18.04
    steps:
    - template: templates/unix.yaml
  - job: macOS
    pool:
      vmImage: macos-latest
    steps:
    - template: templates/unix.yaml