variables:
  # Avoid expensive initialization of dotnet cli, see: https://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
steps:
- template: templates/bootstrap.yaml
- pwsh: |
    ./build.ps1 -Configuration 'Release' -PSVersion 6
  displayName: 'Full Build'
- template: templates/test.yaml
