steps:
- template: templates/bootstrap.yaml
- pwsh: |
    ./build.ps1 -Configuration 'Release' -All
    ./PSCompatibilityCollector/build.ps1 -Configuration 'Release' -Framework 'netstandard2.0'
    Invoke-AppveyorTest -CheckoutPath $env:BUILD_SOURCESDIRECTORY
  displayName: 'PowerShell Script'
