variables:
  # Avoid expensive initialization of dotnet cli, see: https://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
steps:
- template: templates/bootstrap.yaml
- pwsh: |
    ./build.ps1 -Configuration 'Release' -All
    ./PSCompatibilityCollector/build.ps1 -Configuration 'Release' -Framework 'netstandard2.0'
    Invoke-AppveyorTest -CheckoutPath $env:BUILD_SOURCESDIRECTORY
  displayName: 'PowerShell Script'
