variables:
  pwsh: false
steps:
- template: templates/bootstrap.yaml
  parameters:
    pwsh: $(pwsh)
- powershell: |
   Import-Module .\tools\appveyor.psm1
    ./build.ps1 -Configuration 'Release' -PSVersion 5
  displayName: 'Build'
- template: templates/test.yaml
  parameters:
    pwsh: $(pwsh)