# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
# This pipeline will be extended to the OneBranch template
name: PSSA-Release-$(Build.BuildId)
trigger: none
pr:
  branches:
    include:
    - master
    - release*
variables:
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 1
  - name: POWERSHELL_TELEMETRY_OPTOUT
    value: 1
  - name: WindowsContainerImage
    value: onebranch.azurecr.io/windows/ltsc2022/vse2022:latest
resources:
  repositories:
  - repository: onebranchTemplates
    type: git
    name: OneBranch.Pipelines/GovernedTemplates
    ref: refs/heads/main
extends:
  template: v2/OneBranch.Official.CrossPlat.yml@onebranchTemplates
  parameters:
    featureFlags:
      WindowsHostVersion: '1ESWindows2022'
    customTags: 'ES365AIMigrationTooling'
    globalSdl:
      disableLegacyManifest: true
      sbom:
        enabled: true
        packageName: Microsoft.PowerShell.ScriptAnalyzer
      codeql:
        compiled:
          enabled: true
      asyncSdl: # https://aka.ms/obpipelines/asyncsdl
        enabled: true
        forStages: [Build]
        credscan:
          enabled: true
          scanFolder:  $(Build.SourcesDirectory)\OSS_Microsoft_PSSA
        binskim:
          enabled: true
        apiscan:
          enabled: false

    stages:
    - stage: stagebuild
      displayName: Build and Package Microsoft.PowerShell.ScriptAnalyzer
      jobs:
      - job: sdksearch
        displayName: SDK search
        variables:
        - name: ob_outputDirectory
          value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
        - name: repoRoot
          value: $(Build.SourcesDirectory)\OSS_Microsoft_PSSA
        - name: ob_sdl_tsa_configFile
          value: $(Build.SourcesDirectory)\OSS_Microsoft_PSSA\.config\tsaoptions.json
        - name: signSrcPath
          value: $(repoRoot)/out
        # the next job signs, so skip sbom generation, and signing validation
        - name: ob_sdl_codeSignValidation_excludes
          value: -|**\*
        - name: ob_sdl_sbom_enabled
          value: false
        pool:
          type: windows
        steps:
        - checkout: self

        - pwsh: |
            dir C:\dotnet.exe -recurse -erroraction:silentlycontinue
          displayName: Search for dotnet.exet

      - job: jobbuild
        displayName: Build Microsoft.PowerShell.ScriptAnalyzer Files
        variables:
        - name: ob_outputDirectory
          value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
        - name: repoRoot
          value: $(Build.SourcesDirectory)\OSS_Microsoft_PSSA
        - name: ob_sdl_tsa_configFile
          value: $(Build.SourcesDirectory)\OSS_Microsoft_PSSA\.config\tsaoptions.json
        - name: signSrcPath
          value: $(repoRoot)/out
        # the next job signs, so skip sbom generation, and signing validation
        - name: ob_sdl_codeSignValidation_excludes
          value: -|**\*
        - name: ob_sdl_sbom_enabled
          value: false
        pool:
          type: windows
        steps:
        - checkout: self

        - pwsh: |
            if (-not (Test-Path $(repoRoot)/.config/tsaoptions.json)) {
              Get-ChildItem $(Build.SourcesDirectory) -recurse -ErrorAction SilentlyContinue
              throw "tsaoptions.json does not exist under $(repoRoot)/.config"
            }
          displayName: Test if tsaoptions.json exists

        - task: UseDotNet@2
          displayName: 'Install .NET dependencies'
          inputs:
            packageType: 'sdk'
            useGlobalJson: true
            # this is to ensure that we are installing the dotnet at the same location as container by default install the dotnet sdks
            # This prevents signing from breaking
            installationPath: 'C:\Program Files\dotnet\'
            workingDirectory: $(repoRoot)

        # this is installing .NET
        - pwsh: |
            Set-Location "$(repoRoot)"
            try { ./build.ps1 -Configuration Release -All } catch { throw $_ }
          displayName: Execute build

        - task: CopyFiles@2
          displayName: "Copy Files for 'publish build directory' publish task"
          inputs:
            SourceFolder: "$(signSrcPath)"
            Contents: '**'
            TargetFolder: $(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT

      - job: jobsign
        dependsOn: jobbuild
        displayName: Sign Microsoft.PowerShell.ScriptAnalyzer Files
        variables:
          - name: ob_outputDirectory
            value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
          - name: repoRoot
            value: $(Build.SourcesDirectory)\OSS_Microsoft_PSSA
          - name: ob_sdl_tsa_configFile
            value: $(Build.SourcesDirectory)\OSS_Microsoft_PSSA\.config\tsaoptions.json
          - name: ob_sdl_sbom_enabled
            value: true
          - name: ob_sdl_codeql_compiled_enabled
            value: false
          - name: signSrcPath
            value: $(repoRoot)/out
        pool:
          type: windows
        steps:
        - checkout: self

        - task: DownloadPipelineArtifact@2
          displayName: 'Download build files'
          inputs:
            targetPath: $(signSrcPath)
            artifact: drop_stagebuild_jobbuild

        - pwsh: |
            Set-Location "$(signSrcPath)"
            dir -recurse *
          displayName: Capture artifacts

        - task: onebranch.pipeline.signing@1
          displayName: Sign 1st party files
          inputs:
            command: 'sign'
            signing_profile: external_distribution
            files_to_sign: '**\*.psd1;**\*.psm1;**\*.ps1xml;**\Microsoft*.dll'
            search_root: $(signSrcPath)

        - task: onebranch.pipeline.signing@1
          displayName: Sign 3rd Party files
          inputs:
            command: 'sign'
            signing_profile: 135020002
            files_to_sign: '**/Pluralize*.dll;**/Newtonsoft*.dll'
            search_root: $(signSrcPath)

        - task: CopyFiles@2
          displayName: "Copy Files for 'publish build directory' publish task"
          inputs:
            SourceFolder: "$(signSrcPath)"
            Contents: '**'
            TargetFolder: $(ob_outputDirectory)

      - job: nupkg
        dependsOn: jobsign
        displayName: Package Microsoft.PowerShell.ScriptAnalyzer
        variables:
          - name: ob_outputDirectory
            value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
          - name: repoRoot
            value: $(Build.SourcesDirectory)\OSS_Microsoft_PSSA
          - name: ob_sdl_tsa_configFile
            value: $(Build.SourcesDirectory)\OSS_Microsoft_PSSA\.config\tsaoptions.json
          - name: ob_sdl_sbom_enabled
            value: false
          - name: ob_sdl_codeql_compiled_enabled
            value: false
          - name: signOutPath
            value: $(repoRoot)/signed
        pool:
          type: windows
        steps:
        - checkout: self

        - pwsh: |
            if (-not (Test-Path $(repoRoot)/.config/tsaoptions.json)) {
              Get-ChildItem $(Build.SourcesDirectory) -recurse -ErrorAction SilentlyContinue
              throw "tsaoptions.json does not exist under $(repoRoot)/.config"
            }
          displayName: Test if tsaoptions.json exists

        - task: DownloadPipelineArtifact@2
          displayName: 'Download build files'
          inputs:
            targetPath: $(signOutPath)
            artifact: drop_stagebuild_jobbuild

        - pwsh: |
            Set-Location "$(signOutPath)"
            dir -recurse *
          displayName: Capture artifacts

        - pwsh: |
            Set-Location "$(repoRoot)"
            ./build -BuildNupkg -CopyManifest -signed
          displayName: Create nupkg for publishing

        - task: onebranch.pipeline.signing@1
          displayName: Sign nupkg
          inputs:
            command: 'sign'
            signing_profile: external_distribution
            files_to_sign: '**\*.nupkg'
            search_root: $(signOutPath)

        - task: CopyFiles@2
          displayName: "Copy Files for 'Publish module nupkg' publish task"
          inputs:
            Contents: "$(signOutPath)/PSScriptAnalyzer.$(moduleVersion).nupkg"
            TargetFolder: $(ob_outputDirectory)
